spring:
  main:
    web-application-type: none
  kafka:
    producer:
      bootstrap-servers:
      - localhost:19092
      - localhost:19093
      key-serializer:
        org.apache.kafka.common.serialization.StringSerializer
      value-serializer:
        org.formation.model.JsonSerializer 
